### PR TITLE
Add alwaysVisible and unbindWheel attributes

### PR DESCRIPTION
**Pull request by pajcho**
This adds 2 new attributes "always-visible" and "unbind-wheel" to directive

**always-visible** option will make scroller bar to be visible at all times, while **unbind-wheel** will unbind mouse wheel from container and you will be able to scroll content only by keyboard arrows or by dragging scroll bar. This can be useful if there are multiple tables on same page and you don't want to interrupt page scrolling if your mouse hovers over table

Example usage: `<perfect-scrollbar always-visible="true" unbind-wheel="true">`

Options can also be set to "false" in order to disable them

Idea for always visible was taken from example in perfect-scrollbar repository: https://github.com/noraesae/perfect-scrollbar/blob/17aac6c8c8d93fe87545a4d6704e3854080c689f/examples/always-visible.html

### CODE REVIEW

**Comment by davidh87** [comment]
+1 to the always-visible at least!

**Comment by pedrolopix** [comment]
Why waiting? please merge this!

**Comment by misaizdaleka** [comment]
+1 !!!

**Comment by mukulgupta2507** [comment]
+1

**Comment by isherwood** [comment]
These both appear to be good features. Would you mind updating your PR (or creating a new one) so you get proper credit? I'll get on it right away.

**Comment by pajcho** [comment]
@isherwood I have resolved conflicts. It should be all good now. Let me know if you need any help.

**Comment by isherwood** [comment]
After thinking this through a bit more I'm having second thoughts. To this point we haven't added features that the Perfect Scrollbar plugin doesn't provide. I wonder if these features should be proposed there instead. Hmm...

**Pull request closed without merging**
