### PR TITLE
fix digest/apply issues

### PR DESCRIPTION
**Pull request by luisrudge**
Hi! I was having issues with digest already being in progress.

ACcording to [this](http://stackoverflow.com/a/17958847), you shouldn't be using $apply anyway (i'm not).

This is a fix to that issue.

### CODE REVIEW

**Comment by luisrudge** [comment]
FYI I'm still having those issues.

**Comment by itsdrewmiller** [comment]
Can you point to a URL where the problem can be reproduced?

**Comment by luisrudge** [comment]
Unfortunately not, I'm using on a pretty specific sidebar. What's the problem of using $timeout instead of $apply?

**Comment by itsdrewmiller** [comment]
This commit has a syntax error - it would not pass linting.  I would need to see the problem you are encountering to be comfortable trying to fix the change in a way that is correct.

**Comment by luisrudge** [comment]
Ok, I fixed the commit.

**Comment by isherwood** [comment]
Closing due to age and/or inactivity. Please submit a new pull request if you like.

**Pull request closed without merging**
